image: gitpod/workspace-base

env:
  DISTRO: poky-altcfg
  BITBAKE_TARGET: aws-iot-greengrass-lite-with-arpscan
  DEVICE: raspberrypi5-64-with-arpscan

tasks:
  - name: Setup and Configure Build Environment
    command: |
      sudo apt-get update && sudo apt-get install -y --no-install-recommends \
          gawk wget git diffstat unzip texinfo gcc build-essential \
          chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils \
          iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint \
          python3-subunit mesa-common-dev zstd liblz4-tool file locales systemd || {
        echo "ERROR: apt-get install failed" >&2;
        exit 1;
      }

      sudo locale-gen en_US.UTF-8 || { echo "ERROR: locale-gen failed" >&2; exit 1; }
      pip3 install --no-cache-dir pipoe || { echo "ERROR: pip3 install failed" >&2; exit 1; }

      [ ! -d "poky" ] && git clone --depth=1 -b scarthgap git://git.yoctoproject.org/poky.git poky
      [ ! -d "meta-raspberrypi" ] && git clone --depth=1 -b scarthgap git://git.yoctoproject.org/meta-raspberrypi meta-raspberrypi
      [ ! -d "meta-openembedded" ] && git clone --depth=1 -b scarthgap git://git.openembedded.org/meta-openembedded meta-openembedded
      [ ! -d "meta-aws" ] && git clone --depth=1 -b scarthgap https://github.com/aws4embeddedlinux/meta-aws meta-aws
      [ ! -d "meta-rauc-community" ] && git clone --depth=1 -b scarthgap https://github.com/rauc/meta-rauc-community meta-rauc-community
      [ ! -d "meta-rauc" ] && git clone --depth=1 -b scarthgap https://github.com/rauc/meta-rauc meta-rauc

      export BB_ENV_PASSTHROUGH_ADDITIONS="DISTRO DEVICE $BB_ENV_PASSTH-ROUGH_ADDITIONS"
      source ./poky/oe-init-build-env build

      cp "../meta-aws-iot/conf/templates/default/local.conf.sample" conf/local.conf
      cp "../meta-aws-iotconf/templates/default/bblayers.conf.sample" conf/bblayers.conf

      DEVICE_CONF="../meta-aws-iot/conf/devices/$DEVICE/config.conf"
      if [ -f "$DEVICE_CONF" ]; then
        cat "$DEVICE_CONF" >> conf/local.conf
      else
        echo "ERROR: Device config $DEVICE_CONF not found!" >&2;
        exit 1;
      fi

      # move the comment to a new line
      sed -i 's/1K"# Machine/1K"\n# Machine/g' conf/local.conf

      echo "Setup complete! Run 'bitbake $BITBAKE_TARGET' to build."

vscode:
  extensions:
    - ms-vscode.cpptools
    - ms-python.python
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - ms-vscode-remote.remote-containers
    - ms-yocto.yocto-devtools